services:
  omniapotentia-portfolio-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omniapotentia-portfolio-frontend
    environment:
      - VIRTUAL_HOST=omniapotentia.com
      - LETSENCRYPT_HOST=omniapotentia.com
      - LETSENCRYPT_EMAIL=kutay@kutaykaracair.com
    networks:
      - web
    expose:
      - "80"

networks:
  web:
    external: true
